### ISSUE TITLE
Incorrect typings for deaggregate and deaggregateSync methods

### ISSUE THREAD

**Issue by ShyykoSerhiy** [awslabs/kinesis-aggregation#104]
[deaggregate](https://github.com/awslabs/kinesis-aggregation/blob/master/node/index.d.ts#L17) and [deaggregateSync](https://github.com/awslabs/kinesis-aggregation/blob/master/node/index.d.ts#L21) functions use incorrect types for kinesisRecord. All properties inside of the [Kinesis.Types.Record](https://github.com/aws/aws-sdk-js/blob/45336b8bc1e40c859d5c29a67e7ee0ec9380743d/clients/kinesis.d.ts#L756) are in PascalCase, for example [Data](https://github.com/aws/aws-sdk-js/blob/45336b8bc1e40c859d5c29a67e7ee0ec9380743d/clients/kinesis.d.ts#L768) is PascalCased at the same time kinesis-aggregation uses [data](https://github.com/awslabs/kinesis-aggregation/blob/master/node/lib/kpl-deagg.js#L39) in camelCase. 
From [https://github.com/awslabs/kinesis-aggregation/blob/master/node/example/sample-deaggregation.js#L33](this method) it's clear that Kinesis.Types.Record is not the correct type for the parameter and for example [KinesisStreamRecordPayload](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/kinesis-stream.d.ts#L7) from @types/aws-lambda should be used.

I can make a PR if you ok with using @types/aws-lambda as a dep

**Comment by IanMeyers** [comment]
Happy to take a pR on this.
