### ISSUE TITLE
PIP3 version is not consistent with the code in the repo

### ISSUE THREAD

**Issue by orzZXY** [awslabs/kinesis-aggregation#111]
Hi there,

I used this code for Kinesis Data Analytics pre-processing Lambda function.
And I use "pip3 install aws_kinesis_agg" and there is a bug that recordId is missing, after looking into the source code, the code in pip3 package is different from the repo. 
Could you please fix the issue?

Thanks,

**Comment by IanMeyers** [comment]
I've just rebuilt and verified that all changes are in 1.1.3: https://pypi.org/manage/project/aws-kinesis-agg/release/1.1.3/

Sorry for the trouble.
