### ISSUE TITLE
Question about the type in deaggregate function

### ISSUE THREAD

**Issue by yunghoy** [awslabs/kinesis-aggregation#118]
Hi,

Our team is currently using this library with Typescript. I'm casting a type of kinesis records since de-agg in this code uses `KinesisStreamRecordPayload` but it requires `Kinesis.Record` in the signature. [Code](https://github.com/awslabs/kinesis-aggregation/blob/5f84b8b638394ff8b7ee25e1afee957ccf186eae/node/index.d.ts#L17)

Would you be able to check this signature? Since I cannot find the use cases from entire github and I only found several codes in my company's code repository, I'm not sure about this.

Thanks,
Peter

**Comment by IanMeyers** [comment]
Hi - I can't find any reference to `KinesisStreamRecordPayload` that you cite. Can you explain a bit further what issue you are seeing?

**Comment by yunghoy** [comment]
Hi, `KinesisStreamRecordPayload` is in `aws-lambda` but `KinesisStreamRecordPayload` is not that important for this issue.

This is the interface used in [index.d.ts](https://github.com/awslabs/kinesis-aggregation/blob/5f84b8b638394ff8b7ee25e1afee957ccf186eae/node/index.d.ts#L17)
```
deaggregate(kinesisRecord: Kinesis.Types.Record, ...)

// from 'aws-sdk'
export interface Kinesis.Types.Record {
    SequenceNumber: SequenceNumber;
    ApproximateArrivalTimestamp?: Timestamp;
    Data: Data;
    PartitionKey: PartitionKey;
    EncryptionType?: EncryptionType;
}
```

And this is the code in `kpl-deagg.js`
```
function(kinesisRecord: Record, ...)

export interface Record {
    sequenceNumber: any;
    approximateArrivalTimestamp?: any;
    data: any;
    explicitPartitionKey: any;
}
```
https://github.com/awslabs/kinesis-aggregation/blob/5f84b8b638394ff8b7ee25e1afee957ccf186eae/node/lib/kpl-deagg.js#L39
https://github.com/awslabs/kinesis-aggregation/blob/5f84b8b638394ff8b7ee25e1afee957ccf186eae/node/lib/kpl-deagg.js#L95
https://github.com/awslabs/kinesis-aggregation/blob/5f84b8b638394ff8b7ee25e1afee957ccf186eae/node/lib/kpl-deagg.js#L106

**Comment by yunghoy** [comment]
I found that [Relevant Ticket](https://github.com/awslabs/kinesis-aggregation/issues/104) is presented.
