### ISSUE TITLE
Unable to get the Node Aggregation code to work

### ISSUE THREAD

**Issue by mfulleratlassian** [awslabs/kinesis-aggregation#13]
I have tried so many permutations of requires etc I cannot get the RecordAggregator to work in my code.

The README says:
`var agg = require('aws-kinesis-agg');`
`var aggregator = new RecordAggregator();`

but that gives me error: "RecordAggregator is not defined"

Looking at the package.json its main is "./kpl-deagg.js" which has nothing to do with the Aggregation code. Looking around I can only find examples of people using this module for the DeAgg code.

It would be great to get a working sample that works from the npm installed aws-kinesis-agg module.

**Comment by attias** [comment]
I also ran into this problem.
Fixed it with:
var aggregator = require('aws-kinesis-agg/RecordAggregator');

you will also need to do "npm install underscore"

**Comment by IanMeyers** [comment]
Fixed in 0bca64f
