### ISSUE TITLE
aws_kinesis_agg not supported in FIPS mode

### ISSUE THREAD

**Issue by Yc2034** [awslabs/kinesis-aggregation#144]
Library aws aws_kinesis_agg is using md5 which is not being supported in FIPS mode python 3.9.6 (hardened image)

Error Description:
aws_kinesis_agg/__init__.py",line 21, in <module>
0|classifi |  DIGEST_SIZE = hashlib.md5().digest_size
0|classifi | ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips

**Comment by IanMeyers** [comment]
Unfortunately this hash is built into the protobuf protocol and kinesis encoders, and therefore cannot be changed without altering the digest and therefore the message structure.
