### ISSUE TITLE
Potential incompatibility with KPL

### ISSUE THREAD

**Issue by behrangsa** [awslabs/kinesis-aggregation#32]
As @pfifer has mentioned in [amazon-kinesis-producer#128](https://github.com/awslabs/amazon-kinesis-producer/issues/128#issuecomment-326633228) (emphasis mine):

> In addition to this the KPL publishes to a stream, and not a specific shard. _**If two user records are destined for different shards they will never be aggregated together**_.

However kinesis-aggregation seems to aggregate user records into an `AggRecord` and then a `PutRecordRequest` even if they must end up in different shards. This could break KPL compatible clients (e.g. those using KCL).

**Comment by brentnash** [comment]
Is this potentially a duplicate of https://github.com/awslabs/kinesis-aggregation/issues/11?

Currently it is incumbent on the user of this project to ensure that they're only aggregating records destined for the same partition key or explicit hash key.  There is a change in the works to set either the PK or EHK at AggRecord creation time to enforce this behavior.

You are correct about the potential incompatibility, the KCL will currently drop records in an aggregated record if they are received on one shard, but destined for another.

FWIW, I just finished up spinning up a new test stack with a stream backed by Node/Python/Java lambda functions (with the deaggregators from this project) as well as a Java-based KCL app to flesh out these types of issues.

**Comment by behrangsa** [comment]
@brentnash Thanks. You are right, this is a duplicate of #11. I will close this and just watch that issue.
