### ISSUE TITLE
Failed to forward Kinesis records to destination stream

### ISSUE THREAD

**Issue by AEKurt** [awslabs/kinesis-aggregation#33]
I cannot write aggregated data to my kinesis stream. My lambda function and kinesis stream are in the same account. My lambda can read data from a-stream however cannot write b-stream.
Im getting this error,
ERROR: Failed to forward Kinesis records to destination stream: Unable to execute HTTP request: Connect to kinesis.us-east-1.amazonaws.com:443 [kinesis.us-east-1.amazonaws.com/54.239.22.11] failed: connect timed out

**Comment by brentnash** [comment]
Is your Lambda running in a VPC by chance?

**Comment by AEKurt** [comment]
Not by chance. Intentionally we have put our lambda in vpc. What could be problem ?

**Comment by brentnash** [comment]
I'm not sure how the Lambda/Kinesis integration for reading works, but for publishing, it seems like the request is getting dropped by a firewall or network rule somewhere.  Kinesis is not directly accessible from within a VPC (i..e it doesn't support VPC endpoints), so a request from your Lambda needs get out to the Internet to get to Kinesis.

From a public subnet, you'd need to confirm that port 443 is allowed from:

Lambda -> Internet Gateway -> Kinesis

From a private subnet, you'd need to confirm that port 443 is allowed from:

Lambda -> NAT -> Internet Gateway -> Kinesis

Double-check 443 outbound on your Lambda security group, your NAT rules (if they exist), your ACLs, etc.  You could try turn on VPC flow logs to help isolate the problem.

I'll double-check when I get a chance, but it seems unlikely it's a code problem unless we're configured to talk to a non-existent endpoint or something weird like that.

**Comment by AEKurt** [comment]
Thank you for your help. We have directly give internet access to our subnet, however we did not use nat. We have solved problem with using nat.

**Comment by brachipa** [comment]
No need NAT, you can do it also with VPC endpoint:
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html
And that is how to do it to Kinesis:
https://docs.aws.amazon.com/streams/latest/dev/vpc.html

Works for me :) and match cheaper.

If you will read the NAT pricing documnentation they are also recommending this:
https://aws.amazon.com/vpc/pricing/
read the note at the end:
```
Note: To avoid the NAT Gateway Data Processing charge in this example, you could setup a Gateway Type VPC endpoint and route the traffic to/from S3 through the VPC endpoint instead of going through the NAT Gateway. There is no data processing or hourly charges for using Gateway Type VPC endpoints. For details on how to use VPC endpoints, please visit VPC Endpoints Documentation.
```
