### ISSUE TITLE
Unable to import module 'lambda_function': bad magic number in 'google.protobuf': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by rob-dempsey-esure** [awslabs/kinesis-aggregation#52]
Hi

When trying to build for python 3.6 I get the following message

Unable to import module 'lambda_function': bad magic number in 'google.protobuf': b'\x03\xf3\r\n'

Is this because protobuf is only for Python :: 3.4

Thanks

Rob

**Comment by brentnash** [comment]
I have a version of the this library running right now on AWS Lambda with Python 3.6.x, so I don't think that's the issue.

I've generally seen that error when building and packaging on one version of Python (e.g. 2.7.x) and then deploying to a different version of Python on Lambda (e.g. 3.6.x).

Particularly, it's easy to get caught by stale .pyc files that are getting packed up.  For more details:  https://stackoverflow.com/a/514395/159658

I'd recommend wiping out all of your build artifacts (build folder, pyc files, etc.) and then build from scratch and ensure you're building with the same version of Python that you're going to deploy to and see if that does it.

**Comment by rob-dempsey-esure** [comment]
Thanks for the reply

I was using the Data Science Anaconda release of python 3.6.  I spun up a new EC2 and used the one from the yum repo I got it all to work.

Have not had a chance to dig into the detail, but just want to make people aware to try something different if an error such as this pops up again.

Rob

**Comment by brentnash** [comment]
Definitely appreciate you raising the issue.  I ran into it a few times accidentally due to having Python 2.7.x and Python 3.6.x installed concurrently on Windows.

I'll think about if there's anything we could be doing better in the project.  Maybe making sure that we wipe .pyc files in all build scenarios so the stale ones from incorrect versions don't hang around.
