### ISSUE TITLE
Deaggregator does not set approximateArrivalTimestamp in the created record

### ISSUE THREAD

**Issue by ferozed** [awslabs/kinesis-aggregation#60]
When a record is deaggregated from the input record, a bunch of fields are populated into the output record. However, `approximateArrivalTimestamp` is not populated. This is needed for applications that need to know the latency of the record.

**Comment by brentnash** [comment]
Thank you for catching that @ferozed !  Will try to integrate that sometime soon.

**Comment by ferozed** [comment]
Thank you! Glad to help.

**Comment by ferozed** [comment]
hi! @brentnash Can you merge this pull request ? It is a simple change.

**Comment by IanMeyers** [comment]
Working on this now

**Comment by joebowen** [comment]
I opened up PR #72 to fix the issues with the test cases caused by PR #61
