### ISSUE TITLE
Missing index.d.ts within files option of package.json

### ISSUE THREAD

**Issue by Toltar** [awslabs/kinesis-aggregation#73]
Hi guys,

I was recently working with this library in node/typescript but could not import the types. I noticed you added the `index.d.ts` file within #57, but did not add it to the files option in `package.json`. I would be glad to open a PR to fix this.

Thanks,
Matt

**Comment by Toltar** [comment]
@IanMeyers ?

**Comment by IanMeyers** [comment]
This is merged
