### ISSUE TITLE
Implement a Java version based on the AWS Java SDK 2.0 

### ISSUE THREAD

**Issue by greylurk** [awslabs/kinesis-aggregation#90]
The AWS Java SDK 2.0 doesn't have any support for aggregate records in Kinesis, but this library uses the Kinesis message models from the 1.11.x AWS Java SDK.  

If this were updated to use the 2.0 models, it would resolve a functionality gap in the 2.0 SDK.

**Comment by IanMeyers** [comment]
This was just pushed today in fe27a9d

**Comment by greylurk** [comment]
The deaggregator for the V2 api looks complete, but I don't see any support for V2 in the aggregator?

**Comment by IanMeyers** [comment]
Hello,

That's correct. We've not yet shipped the V2 Aggregator Support. Hopefully get time to look at this next week.

Ian

**Comment by IanMeyers** [comment]
Happy to take a pull request if you want to work ahead :)

**Comment by IanMeyers** [comment]
Just pushed https://github.com/awslabs/kinesis-aggregation/pull/97. Let me know if you have any issues. Thx!
